### ISSUE TITLE
libgeotiff dev location has moved

### ISSUE THREAD

**Issue by hobu** [conda-forge/geotiff-feedstock#13]
libgeotiff development location now lives on github at https://github.com/OSGeo/libgeotiff and the recipe should be updated. The announcement was made at https://lists.osgeo.org/pipermail/geotiff/2018-December/000847.html

Additionally, the next major release of libgeotiff is going to change the dependency relationships of these projects significantly. This is all a result of the gdalbarn.com efforts that @rouault has been grinding through. Here's a short synopsis:

* PROJ 6.0 will be released with support for SQLite-based dictionaries, late-binding datum shifts, and a full implementation of a OGC Well Known Text SRS engine. PROJ will be dependent on SQLite going forward.
* libgeotiff 1.5 (or 2.0) will be dependent on PROJ 6 for its dictionaries (replacing the CSV files)
* GDAL 2.5 will be dependent on PROJ 6 for its dictionaries and WKT engine (replacing the CSV files)

Find out more at gdalbarn.com

Howard

**Comment by ocefpaf** [comment]
Thanks for the heads up.

**Comment by ocefpaf** [comment]
I believe we can close this. We are building geotiff 1.5.1 from the new source, proj4 6 has sqlite as a dependency. We are only waiting on gdal 2.5.

Thanks again @hobu!
