### ISSUE TITLE
Activation scripts should be POSIX compliant

### ISSUE THREAD

**Issue by omad** [conda-forge/geotiff-feedstock#56]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I'm attempting to use [tox-conda](https://github.com/tox-dev/tox-conda) to create and activate conda environments, and it reports error messages like:

    sh: 6: /home/omad/miniconda3/envs/odc-core/etc/conda/activate.d/geotiff-activate.sh: [[: not found

This could be fixed within tox-conda by using `/bin/bash` instead of `/bin/sh`, however, I think it actually points to an issue with the activation scripts in this repo.

The [Deep dive: conda init and activate — conda 4.13.0 documentation](https://docs.conda.io/projects/conda/en/4.13.x/dev-guide/deep-dive-activation.html#activation-deactivation-scripts) shows that activate/deactivate scripts are *sourced* by the executing shell, not run as independent scripts. This means the `#!` leading line is being ignored (and as such is misleading), and the activation scripts only work with `/bin/bash`.

They should be rewritten to be POSIX compliant.

 

### Installed packages

```shell
not relevant
```

### Environment info

```shell
active environment : odc-core
    active env location : /home/omad/miniconda3/envs/odc-core
            shell level : 1
       user config file : /home/omad/.condarc
 populated config files : /home/omad/.condarc
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=6.2.6=0
                          __unix=0=0
       base environment : /home/omad/miniconda3  (writable)
      conda av data dir : /home/omad/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/omad/miniconda3/pkgs
                          /home/omad/.conda/pkgs
       envs directories : /home/omad/miniconda3/envs
                          /home/omad/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.2 requests/2.31.0 CPython/3.10.12 Linux/6.2.6-76060206-generic pop/22.04 glibc/2.35
                UID:GID : 1000:1000
             netrc file : /home/omad/.netrc
           offline mode : False
```

**Comment by gillins** [comment]
Happy to receive a PR for this :smile:  I know we had a lot of trouble with `libxml2` doing this, I think https://www.shellcheck.net/ helped in the end.
